### ISSUE TITLE
我尝试安装，但是出现了一些错误。  I tried to install, but encountered some errors.

### ISSUE THREAD

**Issue by rebron1900** [datopian/flowershow#534]
ERROR  Failed to clone Flowershow template into D:\developer\.flowershow. This may be a problem with Flowershow. Please let us know about it by submitting an issue: https://github.com/flowershow/flowershow/issues.
ZlibError: zlib: unexpected end of file
    at Unzip.write (C:\Users\me\AppData\Local\npm-cache\_npx\fb2b4b350a863983\node_modules\degit\dist\index-688c5d50.js:1322:22)
    at Unzip.flush (C:\Users\me\AppData\Local\npm-cache\_npx\fb2b4b350a863983\node_modules\degit\dist\index-688c5d50.js:1273:10)
    at Unzip.end (C:\Users\me\AppData\Local\npm-cache\_npx\fb2b4b350a863983\node_modules\degit\dist\index-688c5d50.js:1279:10)
    at Unpack.end (C:\Users\me\AppData\Local\npm-cache\_npx\fb2b4b350a863983\node_modules\degit\dist\index-688c5d50.js:3989:21)
    at Yallist.<anonymous> (C:\Users\me\AppData\Local\npm-cache\_npx\fb2b4b350a863983\node_modules\degit\dist\index-688c5d50.js:903:18)
    at Yallist.forEach (C:\Users\me\AppData\Local\npm-cache\_npx\fb2b4b350a863983\node_modules\degit\dist\index-688c5d50.js:240:8)
    at ReadStream.emit (C:\Users\me\AppData\Local\npm-cache\_npx\fb2b4b350a863983\node_modules\degit\dist\index-688c5d50.js:900:18)
    at ReadStream.emit (C:\Users\me\AppData\Local\npm-cache\_npx\fb2b4b350a863983\node_modules\degit\dist\index-688c5d50.js:3262:22)
    at [maybeEmitEnd] (C:\Users\me\AppData\Local\npm-cache\_npx\fb2b4b350a863983\node_modules\degit\dist\index-688c5d50.js:864:12)
    at ReadStream.end (C:\Users\me\AppData\Local\npm-cache\_npx\fb2b4b350a863983\node_modules\degit\dist\index-688c5d50.js:744:27) {
  code: 'Z_BUF_ERROR',
  errno: -5,
  recoverable: false,
  file: 'C:\\Users\\me\\.degit\\github\\datopian\\flowershow/2ca757f820fb17c15298669e373b2bc5f2b7d616.tar.gz',
  cwd: 'D:\\developer\\.flowershow',
  tarCode: 'TAR_ABORT'
}

**Comment by demenech** [comment]
hey @rebron1900 

Thank you for reporting this.

I tried to reproduce the issue on Window 10 but no success so far, the install went fine for me. Can you share more info about the version of Node, NPM and Windows that you have on your system?

After some research, I'd like to ask you to delete `C:\Users\me\.degit` and see if that helps.

___

@olayway according to this issue https://github.com/Rich-Harris/degit/issues/313 I think we should consider migrating from degit to tiged.

**Comment by rebron1900** [comment]
谢谢，已经正常工作了。
